name: SOAT | FIAP | CI/CD Completo - Qualidade e Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY_NAME: soat-challenge-repository
  EKS_CLUSTER_NAME: soat-challenge-eks-cluster
  # Usa o SHA do commit ou o SHA da cabeça do PR para a tag da imagem
  IMAGE_TAG: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  # JOB 1: Validação de Qualidade (Roda em PRs e na Main)
  quality_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Instalar dependências
        run: npm ci

      - name: Validar Build (Compilação)
        run: npm run build

      - name: Rodar testes com cobertura (Mínimo 70%)
        run: npm run test:cov
        env:
          DB_HOST: localhost
          DB_PORT: 27017
          DB_USER: admin
          DB_PASSWORD: password
          DB_NAME: test_db
          PORT: 3000

  # JOB 2: Build Docker e Deploy no EKS (Só roda na Main e se o Quality Check passar)
  build_and_deploy:
    needs: quality_check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar as credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Fazer login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir e enviar a imagem Docker para o ECR
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_NAME }}:${{ env.IMAGE_TAG }}
          echo "Building and pushing image: $IMAGE_URI"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Instalar o kubectl
        uses: azure/setup-kubectl@v3

      - name: Configurar o kubeconfig para o cluster EKS
        run: aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Implantação no EKS
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_NAME }}:${{ env.IMAGE_TAG }}
          kubectl get deployments -A
          kubectl set image deployment/cart cart="$IMAGE_URI"
          kubectl rollout status deployment/cart
